DROP DATABASE IF EXISTS rieltoragency;
CREATE DATABASE IF NOT EXISTS rieltoragency;
USE rieltoragency;

CREATE TABLE REGION (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	REGION CHAR(60) NOT NULL
);              
CREATE TABLE HOUSE (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	REGION_ID int UNSIGNED NOT NULL,
	ADRESS CHAR(150) NOT NULL,
	LEVELS int,
	BUILT_YEAR date,
	LAST_REPAIR date
);
ALTER TABLE HOUSE ADD CONSTRAINT HOUSE_REGION
	FOREIGN KEY (REGION_ID)
	REFERENCES REGION(ID) ON DELETE CASCADE;
Describe HOUSE; 


CREATE TABLE OBJECT_TYPE (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE CHAR(60) NOT NULL
);
CREATE TABLE BALCONY (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE CHAR(60) NOT NULL
);
CREATE TABLE TOILET (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE CHAR(60) NOT NULL
);
CREATE TABLE HEAT (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE CHAR(60) NOT NULL
);
CREATE TABLE STOVE (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE CHAR(60) NOT NULL
); 
CREATE TABLE OBJECT_STATE (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE CHAR(60) NOT NULL
);
CREATE TABLE OBJECT (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	HOUSE_ID int UNSIGNED NOT NULL,
	OBJECT_TYPE_ID int UNSIGNED NOT NULL,
	ROOMS int NOT NULL,
	AREA int NOT NULL,
	LEVEL int NOT NULL,
	PORCH int,
	BALCONY_ID int UNSIGNED,
	TOILET_ID int UNSIGNED,
	HEAT_ID int UNSIGNED,
	STOVE_ID int UNSIGNED,
	METERS boolean,
	OBJECT_STATE_ID int UNSIGNED
);
ALTER TABLE OBJECT ADD CONSTRAINT OBJECT_HOUSE
	FOREIGN KEY (HOUSE_ID)
	REFERENCES HOUSE(ID) ON DELETE CASCADE;
ALTER TABLE OBJECT ADD CONSTRAINT OBJECT_OBJECT_TYPE
	FOREIGN KEY (OBJECT_TYPE_ID)
	REFERENCES OBJECT_TYPE(ID) ON DELETE CASCADE;
ALTER TABLE OBJECT ADD CONSTRAINT OBJECT_BALCONY
	FOREIGN KEY (BALCONY_ID)
	REFERENCES BALCONY(ID) ON DELETE CASCADE;
ALTER TABLE OBJECT ADD CONSTRAINT OBJECT_TOILET
	FOREIGN KEY (TOILET_ID)
	REFERENCES TOILET(ID) ON DELETE CASCADE;
ALTER TABLE OBJECT ADD CONSTRAINT OBJECT_HEAT
	FOREIGN KEY (HEAT_ID)
	REFERENCES HEAT(ID) ON DELETE CASCADE;
ALTER TABLE OBJECT ADD CONSTRAINT OBJECT_STOVE
	FOREIGN KEY (STOVE_ID)
	REFERENCES STOVE(ID) ON DELETE CASCADE;
ALTER TABLE OBJECT ADD CONSTRAINT OBJECT_OBJECT_STATE
	FOREIGN KEY (OBJECT_STATE_ID)
	REFERENCES OBJECT_STATE(ID) ON DELETE CASCADE;
DESCRIBE OBJECT;

CREATE TABLE ADVERT_TYPE (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE CHAR(60) NOT NULL
);
CREATE TABLE STATE_TYPE (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE CHAR(60) NOT NULL
);
CREATE TABLE ADVERT (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TYPE_ID int UNSIGNED NOT NULL,
	OBJECT_ID int UNSIGNED NOT NULL,
	COST int UNSIGNED NOT NULL,
	ADVERT_DATE date NOT NULL,
	STATE_ID int UNSIGNED NOT NULL,
	COMMUNAL boolean
);
ALTER TABLE ADVERT ADD CONSTRAINT ADVERT_ADVERT_TYPE
	FOREIGN KEY (TYPE_ID)
	REFERENCES ADVERT_TYPE(ID) ON DELETE CASCADE;
ALTER TABLE ADVERT ADD CONSTRAINT ADVERT_OBJECT
	FOREIGN KEY (OBJECT_ID)
	REFERENCES OBJECT(ID) ON DELETE CASCADE;
ALTER TABLE ADVERT ADD CONSTRAINT ADVERT_STATE_TYPE
	FOREIGN KEY (STATE_ID)
	REFERENCES STATE_TYPE(ID) ON DELETE CASCADE;
DESCRIBE ADVERT;

CREATE TABLE STATE_TRACK (
	ID int UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	LAST_STATE_ID int UNSIGNED NOT NULL,
	DATE_OF_CHANGE date NOT NULL,
	ADVERT_ID int UNSIGNED NOT NULL
);
ALTER TABLE STATE_TRACK ADD CONSTRAINT STATE_TRACK_STATE_TYPE
	FOREIGN KEY (LAST_STATE_ID)
	REFERENCES STATE_TYPE(ID) ON DELETE CASCADE;
ALTER TABLE STATE_TRACK	ADD CONSTRAINT STATE_TRACK_ADVERT
	FOREIGN KEY (ADVERT_ID)
	REFERENCES ADVERT(ID) ON DELETE CASCADE;
DESCRIBE ADVERT;

SHOW TABLES;
